In [1]:
import numpy

In [2]:
import numpy as np

In [4]:
myarray_1 = np.array([[2,3,4],
                    [3,4,5]])

In [5]:
myarray_1

array([[2, 3, 4],
       [3, 4, 5]])

In [6]:
mylist1 = [1,2,3,4]

In [7]:
mylist2 = [[1,2,3,4],
          [5,6,7,8]]

In [8]:
arr1 = np.array(mylist1)

In [9]:
arr2 = np.array(mylist2)

In [10]:
arr1.shape

(4,)

In [11]:
arr2.shape

(2, 4)

In [12]:
arr2[1,1]

6

In [13]:
arr2[0,0]

1

In [14]:
arr2[0,3]

4

In [15]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [16]:
arr2d[:,3] #4번째 열을 가져오라는 뜻

array([ 4,  8, 12])

In [17]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [18]:
arr2d[:2,3]

array([4, 8])

In [19]:
arr2d[:1,3]

array([4])

In [20]:
arr2d[:3,3]

array([ 4,  8, 12])

In [21]:
arr2d[:2,2] # 3열의 3번째 요소 미만

array([3, 7])

In [22]:
arr2d[1,3:] #1행의 4번째요소 이상

array([8])

In [23]:
arr2d[2,2:]

array([11, 12])

In [24]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [25]:
arr2d[[2,1],:]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])