In [4]:
import numpy

In [5]:
import numpy as np

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(start=1, stop=11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(11,1)

array([], dtype=int32)

In [9]:
np.arange(stop=11 ,start=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(start=1, stop=11 , step=2)

array([1, 3, 5, 7, 9])

In [13]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])

In [14]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [15]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [16]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1],
                 [10,9,12,11]])

In [28]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [19]:
np.sort(arr2d)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [26]:
np.sort(arr2d, axis=0)

array([[ 4,  6,  2,  1],
       [ 5,  9,  7,  8],
       [10, 10, 12, 11]])

In [29]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [30]:
arr2d = np.array([[5,6,7,8],
                 [4,3,2,1],
                  [10,9,12,11]])

In [31]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [32]:
np.argsort(arr2d,axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

In [33]:
np.argsort(arr2d,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

In [34]:
a = np.array([[1,2,3],
             [2,3,4]])

In [35]:
np.sum(a)

15

In [36]:
np.sum(a,axis=0)

array([3, 5, 7])

In [37]:
np.sum(a,axis=1)

array([6, 9])

In [38]:
a = np.array([[1,2,3],
             [2,3,4]])

In [39]:
b = np.array([[3,4,5],
             [1,2,3]])

In [40]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [42]:
c = np.array([[1,2],
             [3,4],
             [5,6]])

In [43]:
np.dot(a,c)

array([[22, 28],
       [31, 40]])

In [45]:
a = np.array([[1,2,3],
             [2,3,4]])

In [46]:
b = np.array([[3,3,3],
             [3,3,3]])

In [47]:
a  + b

array([[4, 5, 6],
       [5, 6, 7]])

In [48]:
a  + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [49]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [50]:
a * 3 

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [51]:
a / 3


array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])